// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxA0M8gVviPAe_4m6182mBKuM-bPqA8C4',
    appId: '1:1007787215156:web:5edc5ae97a722fe6e6bd61',
    messagingSenderId: '1007787215156',
    projectId: 'picture-quest-b5a93',
    authDomain: 'picture-quest-b5a93.firebaseapp.com',
    storageBucket: 'picture-quest-b5a93.appspot.com',
    measurementId: 'G-SS5JDW450T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlb1F0-tB6Qu816gREXosevUwAhkEJYZI',
    appId: '1:1007787215156:android:4f3bf3362c9e5120e6bd61',
    messagingSenderId: '1007787215156',
    projectId: 'picture-quest-b5a93',
    storageBucket: 'picture-quest-b5a93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXd29FprHVudq96eXXDdENfTMAcaFNeF8',
    appId: '1:1007787215156:ios:684a9671a309ec62e6bd61',
    messagingSenderId: '1007787215156',
    projectId: 'picture-quest-b5a93',
    storageBucket: 'picture-quest-b5a93.appspot.com',
    iosBundleId: 'com.example.pictureQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXd29FprHVudq96eXXDdENfTMAcaFNeF8',
    appId: '1:1007787215156:ios:bc2f78adb1165f93e6bd61',
    messagingSenderId: '1007787215156',
    projectId: 'picture-quest-b5a93',
    storageBucket: 'picture-quest-b5a93.appspot.com',
    iosBundleId: 'com.example.pictureQuest.RunnerTests',
  );
}
